### ISSUE TITLE
About the input file of LINSIGHT

### ISSUE THREAD

**Issue by xie186** [CshlSiepelLab/LINSIGHT#1]
Hi there,

When I was using LINSIGHT, I got stuck at the step of how to generate the two input files:
1) feature information: for example, I have different peaks in different bed files. But how do I generate a combined matrix for LINSIGHT? Could you please give some details? 
2) genome-wide INSIGHT file: how to generate this file? Could you please give one example of how you generate this file? Thanks. 
I noticed that in the test data. There is no `beta <beta1> <beta2> <beta3>`. But in INSIGHT manual, Input File for INSIGHT-EM should have `<beta1> <beta2> <beta3>`, I'm confused. 

Thanks for the great tool. 

Best,
Shaojun

**Comment by huangyifeicmb** [comment]
Hi Shaojun,

Thanks for your interest on our work. Please see my comments below.

Best,
Yifei

1. You could use unionBedGraphs in bedtools to merge multiple bedGraph files. Each input file should have four columns: chrom, start, end, and value (1/0 for presence/absence of peaks, for example). Make sure that the input bedGraph files are sorted properly.

2. We used an in-house pipeline developed by Ilan Gronau and Brad Gulko to generate the genome-wide INSIGHT file. This pipeline is pretty complicated and is not ready to be released publicly. Which species are you working on? If it is human, I suggest to use the genome-wide INSIGHT file provided in our LINSIGHT paper.

3. In LINSIGHT, we use command arguments to set betas. For example, command argument "-b1 0.7567672441 -b2 0.2053143291" means beta1 is equal to 0.7567672441 while beta2 is equal to 0.2053143291. Beta3 is equal to 1 - beta1 - beta2 by definition.

**Comment by xie186** [comment]
Hi Yifei,
Thank you for your reply. 
I'm trying to use LINSIGHT on maize genome, so I can't use the data provided in LINSIGHT paper. Do you have a timeline of when the pipeline will be ready to release publicly? 
Best,
Shaojun

**Comment by xie186** [comment]
Hi Yifei,
As you can see in the last comment, we are working on a project on maize in which the prediction results of LINSIGHT may provide a big improvement. I'm wondering whether it's possible that we can collaborate on this. We can talk into details via email (xie186@purdue.edu). Again - thanks for the great work of LINSIGHT. 
Best,
Shaojun
