### ISSUE TITLE
Different formats of precalculated values

### ISSUE THREAD

**Issue by moonso** [CshlSiepelLab/LINSIGHT#2]
Hi, thanks for a nice resource!

Would it be possible for you to offer the pre calculated values in different file formats than bigwig?
[Cadd](http://cadd.gs.washington.edu/download) for example is in a `.tsv` format that can be used with tabix etc.
It would be nice if as many similar resources are available in similar formats, we could then keep down the number of dependencies for software that use the resources.

Best,

Måns

**Comment by huangyifeicmb** [comment]
Hi Måns,

I converted precomputed LINSIGHT scores to tsv format. You can download it from the following links.

Best,
Yifei

score file: http://compgen.cshl.edu/%7Eyihuang/tracks/LINSIGHT_SNVs.tsv.gz
index file: http://compgen.cshl.edu/%7Eyihuang/tracks/LINSIGHT_SNVs.tsv.gz.tbi
