### ISSUE TITLE
Feature descriptions

### ISSUE THREAD

**Issue by davek44** [CshlSiepelLab/LINSIGHT#6]
Great work here! I was wondering if you didn't mind describing the feature columns in your file here: http://compgen.cshl.edu/~yihuang/LINSIGHT/genomic_feature.bed.gz. Presently, the header line contains chr, start, end and then 48 ones.

**Comment by huangyifeicmb** [comment]
Hi David,

The header file can be downloaded here: http://compgen.cshl.edu/~yihuang/LINSIGHT/LINSIGHT_feature_list.txt

Best,

Yifei

**Comment by davek44** [comment]
Thanks!
