### ISSUE TITLE
404 not found error for pre-computed score

### ISSUE THREAD

**Issue by ZhenCaoJack** [CshlSiepelLab/LINSIGHT#7]
Hi there, 

Currently I an trying to score a large mount of disease related variants using the pre-compute LINSIGHT score.
 
However, I get a 404 not found error for the download link. I have searched for some time but get no result.  Is the download link moved to somewhere else ?

Best regards!
Zhen Cao

**Comment by ramaniritika** [comment]
Hello Zhen,

Sorry about that. This link should work - http://compgen.cshl.edu/LINSIGHT/
Please let me know if you still have trouble accessing the LINSIGHT scores.

Thanks!
Ritika

**Comment by ZhenCaoJack** [comment]
Hi Ritika,

Thanks a lot, all the download links work !

And I think this issue may be termed as 'closed'.

Best regards!
Zhen Cao
